# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('city_id', models.IntegerField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=45)),
                ('morn_temperature', models.CharField(blank=True, max_length=45, null=True)),
                ('morn_weather', models.CharField(max_length=45)),
                ('morn_rainfall', models.CharField(blank=True, max_length=45, null=True)),
                ('noon_temperature', models.CharField(blank=True, max_length=45, null=True)),
                ('noon_weather', models.CharField(max_length=45)),
                ('noon_rainfall', models.CharField(blank=True, max_length=45, null=True)),
                ('current_date', models.DateField()),
            ],
            options={
                'db_table': 'weather',
                'managed': False,
            },
        ),
    ]
